# Dongle (central) — only applied to sofle_dongle build

# Dongle has no RGB LEDs
CONFIG_ZMK_RGB_UNDERGLOW=n

# Dongle has no encoders
CONFIG_EC11=n

# ── Prospector display ────────────────────────────────────────────────────────
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
